image: python

# TODO: Trigger Docker Pipeline
# TODO: Build API Documentation

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"
  PIPENV_VENV_IN_PROJECT: "true"

cache:
  paths:
    - .cache/pip
    - .venv/

stages:
  - test

before_script:
  - pip install pipenv
  - pipenv install --dev --deploy

test:
  stage: test
  script:
    - pipenv run test:unit -q